# INSERT YOUR CONFIG:

# YOUR ID:
OWNER_ID = 123456789
# DEFAULT PREFIX
DEFAULT_PREFIX = "_"
# BOT TOKEN:
TOKEN = ""

# MONGODB STUFF:
# LINK TO YOUR DB
# REPLACE THE <password> with your password!
CONNECTION = ""
# NAME OF YOUR CLUSTER:
CLUSTER = ""
# NAME OF YOUR DATABASE
DB = ""
# PASSWORD FOR YOUR DB:
#PASSWORD = ""