COGS = ["dataminer.message",
        "dataminer.reaction",
        "dataminer.member",
        "dataminer.status",
        "util.guild_event",
        "cogs.stats",
        "cogs.analysis",
        "cogs.help",
        "util.error",
        "cogs.plot",
        "cogs.config.set",
        "cogs.config.db"]